[tool.poetry]
name = "torchfactors"
version = "0.3.4"
description = "differentiable generalized belief propagation with pytorch"
authors = ["Adam Teichert"]
license = "MIT"
packages = [
    {include="torchfactors", from="src"}
]


[tool.poetry.dependencies]
python = "^3.8"
multimethod = "^1.5"
torch = "^1.9.0"
# torch-semiring-einsum = "^1.0.0"
# opt-einsum = "^3.3.0"
pandas = "^1.3.1"
torchmetrics = "^0.4.0"
tqdm = "^4.61.1"
# torch-optimizer = "^0.1.0"
pytorch-lightning = "^1.3.8"


[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
# pytest-mock = "^3.5.1"
pdoc = "^6.3.1"
flake8 = "^3.8.4"
mypy = "^0.910"
autopep8 = "^1.5.5"
pytest-codeblocks = "^0.11.1"
ipykernel = "^5.5.5"
autoflake = "^1.4"
scalene = "^1.3.6"
py-spy = "^0.3.7"
pandas-stubs = "^1.2.0"
# debugpy = "^1.4.1"
rope = "^0.19.0"


[build-system]
requires = ["poetry-core>=1.1.7"]
build-backend = "poetry.core.masonry.api"
